services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://todouser:todopass@db:5432/tododb
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: